//
#version 460 core

// This vertex shader is used to generate and transform grid vertices
// It takes no input except the gl_VertexID parameter

// gl_VertexID contains the index of the current vertex, which is impliclty generated by glDrawArrays
// or explicitly generated from the content of the GL_ELEMENT_ARRAY_BUFFER by commands such as glDrawElements

#include <data/shaders/chapter04/GLBufferDeclarations.h>
#include <data/shaders/chapter05/GridParameters.h>

layout (location=0) out vec2 uv;

void main()
{
	mat4 MVP = proj * view;

	int idx = indices[gl_VertexID];

	// scales the [-1..+1] rectangle by grid size
	vec3 position = pos[idx] * gridSize;

	gl_Position = MVP * vec4(position, 1.0);

	// output the XZ world coordinates of the vertex inside the uv parameter
	uv = position.xz;
}
